[project]
name = "brick-finder-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.24.0",
    "httpx>=0.24.0",
]
